project:
  type: website
  output-dir: docs

website:
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/alice-pao/
format:
  html:
    theme: yeti
    css: styles.css
    



